# Generated by Django 4.2.2 on 2023-06-28 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(blank=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cnpj",
                    localflavor.br.models.BRCNPJField(
                        db_index=True, max_length=18, unique=True
                    ),
                ),
                ("fantasy_name", models.TextField(blank=True, null=True)),
                ("corporate_name", models.TextField(blank=True, null=True)),
                ("telephone", models.TextField(blank=True, null=True)),
                ("cell_phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("state_registration", models.BooleanField(default=False)),
                ("state_registration_number", models.TextField(blank=True, null=True)),
                (
                    "social_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                ("foundation_date", models.DateField(blank=True, null=True)),
                (
                    "society_type",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "CNAE primário"), (2, "CNAE secundário")],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_person_address",
                        to="core.address",
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_person_billing_address",
                        to="core.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NaturalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(blank=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cpf",
                    localflavor.br.models.BRCPFField(
                        db_index=True, max_length=14, unique=True
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(blank=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("partner_id", models.PositiveIntegerField(db_index=True, null=True)),
                ("percentage", models.FloatField(blank=True, null=True)),
                ("legal_representative", models.BooleanField(default=False)),
                ("guarantor", models.BooleanField(default=False)),
                (
                    "signature",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Assina em conjunto"), (2, "Assina separado")],
                        default=1,
                        null=True,
                    ),
                ),
                ("can_operate", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participation_company",
                        to="scraping.legalperson",
                    ),
                ),
                (
                    "partner_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CNAE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(blank=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=250, null=True
                    ),
                ),
                (
                    "type",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Não definida"),
                            (1015, "Órgão Público do Poder Executivo Federal"),
                            (
                                1023,
                                "Órgão Público do Poder Executivo Estadual ou do Distrito Federal",
                            ),
                            (1031, "Órgão Público do Poder Executivo Municipal"),
                            (1040, "Órgão Público do Poder Legislativo Federal"),
                            (
                                1058,
                                "Órgão Público do Poder Legislativo Estadual ou do Distrito Federal",
                            ),
                            (1066, "Órgão Público do Poder Legislativo Municipal"),
                            (1074, "Órgão Público do Poder Judiciário Federal"),
                            (1082, "Órgão Público do Poder Judiciário Estadual"),
                            (1104, "Autarquia Federal"),
                            (1112, "Autarquia Estadual ou do Distrito Federal"),
                            (1120, "Autarquia Municipal"),
                            (1139, "Fundação Pública de Direito Público Federal"),
                            (
                                1147,
                                "Fundação Pública de Direito Público Estadual ou do Distrito Federal",
                            ),
                            (1155, "Fundação Pública de Direito Público Municipal"),
                            (1163, "Órgão Público Autônomo Federal"),
                            (
                                1171,
                                "Órgão Público Autônomo Estadual ou do Distrito Federal",
                            ),
                            (1180, "Órgão Público Autônomo Municipal"),
                            (1198, "Comissão Polinacional"),
                            (
                                1210,
                                "Consórcio Público de Direito Público (Associação Pública)",
                            ),
                            (1228, "Consórcio Público de Direito Privado"),
                            (1236, "Estado ou Distrito Federal"),
                            (1244, "Município"),
                            (1252, "Fundação Pública de Direito Privado Federal"),
                            (
                                1260,
                                "Fundação Pública de Direito Privado Estadual ou do Distrito Federal",
                            ),
                            (1279, "Fundação Pública de Direito Privado Municipal"),
                            (1287, "Fundo Público da Administração Indireta Federal"),
                            (
                                1295,
                                "Fundo Público da Administração Indireta Estadual ou do Distrito Federal",
                            ),
                            (1309, "Fundo Público da Administração Indireta Municipal"),
                            (1317, "Fundo Público da Administração Direta Federal"),
                            (
                                1325,
                                "Fundo Público da Administração Direta Estadual ou do Distrito Federal",
                            ),
                            (1333, "Fundo Público da Administração Direta Municipal"),
                            (1341, "União"),
                            (2011, "Empresa Pública"),
                            (2038, "Sociedade de Economia Mista"),
                            (2046, "Sociedade Anônima Aberta"),
                            (2054, "Sociedade Anônima Fechada"),
                            (2062, "Sociedade Empresária Limitada"),
                            (2070, "Sociedade Empresária em Nome Coletivo"),
                            (2089, "Sociedade Empresária em Comandita Simples"),
                            (2097, "Sociedade Empresária em Comandita por Ações"),
                            (2127, "Sociedade em Conta de Participação"),
                            (2135, "Empresário (Individual)"),
                            (2143, "Cooperativa"),
                            (2151, "Consórcio de Sociedades"),
                            (2160, "Grupo de Sociedades"),
                            (
                                2178,
                                "Estabelecimento, no Brasil, de Sociedade Estrangeira",
                            ),
                            (
                                2194,
                                "Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira",
                            ),
                            (2216, "Empresa Domiciliada no Exterior"),
                            (2224, "Clube/Fundo de Investimento"),
                            (2232, "Sociedade Simples Pura"),
                            (2240, "Sociedade Simples Limitada"),
                            (2259, "Sociedade Simples em Nome Coletivo"),
                            (2267, "Sociedade Simples em Comandita Simples"),
                            (2275, "Empresa Binacional"),
                            (2283, "Consórcio de Empregadores"),
                            (2291, "Consórcio Simples"),
                            (
                                2305,
                                "Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)",
                            ),
                            (
                                2313,
                                "Empresa Individual de Responsabilidade Limitada (de Natureza Simples)",
                            ),
                            (2321, "Sociedade Unipessoal de Advogados"),
                            (2330, "Cooperativas de Consumo"),
                            (3034, "Serviço Notarial e Registral (Cartório)"),
                            (3069, "Fundação Privada"),
                            (3077, "Serviço Social Autônomo"),
                            (3085, "Condomínio Edilício"),
                            (3107, "Comissão de Conciliação Prévia"),
                            (3115, "Entidade de Mediação e Arbitragem"),
                            (3131, "Entidade Sindical"),
                            (
                                3204,
                                "Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras",
                            ),
                            (3212, "Fundação ou Associação Domiciliada no Exterior"),
                            (3220, "Organização Religiosa"),
                            (3239, "Comunidade Indígena"),
                            (3247, "Fundo Privado"),
                            (3255, "Órgão de Direção Nacional de Partido Político"),
                            (3263, "Órgão de Direção Regional de Partido Político"),
                            (3271, "Órgão de Direção Local de Partido Político"),
                            (3280, "Comitê Financeiro de Partido Político"),
                            (3298, "Frente Plebiscitária ou Referendária"),
                            (3301, "Organização Social (OS)"),
                            (3310, "Demais Condomínios"),
                            (3999, "Associação Privada"),
                            (4014, "Empresa Individual Imobiliária"),
                            (4022, "Segurado Especial"),
                            (4081, "Contribuinte individual"),
                            (4090, "Candidato a Cargo Político Eletivo"),
                            (4111, "Leiloeiro"),
                            (4120, "Produtor Rural (Pessoa Física)"),
                            (5010, "Organização Internacional"),
                            (5029, "Representação Diplomática Estrangeira"),
                            (5037, "Outras Instituições Extraterritoriais"),
                        ],
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cnae_company",
                        to="scraping.legalperson",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
