from django.db import models


class CnaeChoices(models.IntegerChoices):
    PRIMARY_CNAE = 1, 'CNAE primário'
    SECONDARY_CNAE = 2, 'CNAE secundário'

class SubscriptionChoices(models.IntegerChoices):
    SIGN_TOGETHER = 1, 'Assina em conjunto'
    SIGN_SEPARATELY = 2, 'Assina separado'

class SocietyTypeChoices(models.IntegerChoices):
    # Credmei
    UNDEFINED = 1, 'Não definida'
    # 1. Administração Pública
    PUBLIC_BODY_FEDERAL_EXECUTIVE_BRANCH = 1015, 'Órgão Público do Poder Executivo Federal'
    PUBLIC_BODY_STATE_EXECUTIVE_FEDERAL_DISTRICT = 1023, 'Órgão Público do Poder Executivo Estadual ou do Distrito Federal'
    PUBLIC_BODY_MUNICIPAL_EXECUTIVE = 1031, 'Órgão Público do Poder Executivo Municipal'
    PUBLIC_BODY_FEDERAL_LEGISLATIVE = 1040, 'Órgão Público do Poder Legislativo Federal'
    PUBLIC_BODY_STATE_OR_FEDERAL_DISTRICT_LEGISLATIVE = 1058, 'Órgão Público do Poder Legislativo Estadual ou do Distrito Federal'
    PUBLIC_BODY_MUNICIPAL_LEGISLATIVE = 1066, 'Órgão Público do Poder Legislativo Municipal'
    PUBLIC_BODY_FEDERAL_JUDICIARY = 1074, 'Órgão Público do Poder Judiciário Federal'
    PUBLIC_BODY_STATE_JUDICIARY = 1082, 'Órgão Público do Poder Judiciário Estadual'
    FEDERAL_AUTHORITY = 1104, 'Autarquia Federal'
    STATE_OR_FEDERAL_DISTRICT_AUTHORITY = 1112, 'Autarquia Estadual ou do Distrito Federal'
    CITY_AUTHORITY = 1120, 'Autarquia Municipal'
    PUBLIC_FOUNDATION_FEDERAL_PUBLIC_LAW = 1139, 'Fundação Pública de Direito Público Federal'
    PUBLIC_FOUNDATION_STATE_OR_FEDERAL_DISTRICT_PUBLIC_LAW = 1147, 'Fundação Pública de Direito Público Estadual ou do Distrito Federal'
    PUBLIC_FOUNDATION_MUNICIPAL_PUBLIC_LAW = 1155, 'Fundação Pública de Direito Público Municipal'
    PUBLIC_BODY_AUTONOMOUS_FEDERAL = 1163, 'Órgão Público Autônomo Federal'
    PUBLIC_BODY_AUTONOMOUS_STATE_OR_FEDERAL_DISTRICT = 1171, 'Órgão Público Autônomo Estadual ou do Distrito Federal'
    PUBLIC_BODY_AUTONOMOUS_MUNICIPAL = 1180, 'Órgão Público Autônomo Municipal'
    POLYNATIONAL_COMMISSION = 1198, 'Comissão Polinacional'
    PUBLIC_CONSORTIUM_PUBLIC_LAW = 1210, 'Consórcio Público de Direito Público (Associação Pública)'
    PUBLIC_CONSORTIUM_PRIVATE_LAW = 1228, 'Consórcio Público de Direito Privado'
    STATE_OR_FEDERAL_DISTRICT = 1236, 'Estado ou Distrito Federal'
    COUNTY = 1244, 'Município'
    PUBLIC_FOUNDATION_FEDERAL_PRIVATE_LAW = 1252, 'Fundação Pública de Direito Privado Federal'
    PUBLIC_FOUNDATION_PRIVATE_STATE_OR_FEDERAL_DISTRICT_LAW = 1260, 'Fundação Pública de Direito Privado Estadual ou do Distrito Federal'
    PUBLIC_FOUNDATION_MUNICIPAL_PRIVATE_LAW = 1279, 'Fundação Pública de Direito Privado Municipal'
    PUBLIC_FUND_FEDERAL_INDIRECT_ADMINISTRATION = 1287, 'Fundo Público da Administração Indireta Federal'
    PUBLIC_FUND_FOR_STATE_OR_FEDERAL_DISTRICT_INDIRECT_ADMINISTRATION = 1295, 'Fundo Público da Administração Indireta Estadual ou do Distrito Federal'
    PUBLIC_FUND_MUNICIPAL_INDIRECT_ADMINISTRATION = 1309, 'Fundo Público da Administração Indireta Municipal'
    PUBLIC_FUND_FEDERAL_DIRECT_ADMINISTRATION = 1317, 'Fundo Público da Administração Direta Federal'
    PUBLIC_FUND_DIRECT_STATE_OR_FEDERAL_DISTRICT = 1325, 'Fundo Público da Administração Direta Estadual ou do Distrito Federal'
    PUBLIC_FUND_MUNICIPAL_DIRECT_ADMINISTRATION = 1333, 'Fundo Público da Administração Direta Municipal'
    UNION = 1341, 'União'
    #  2. Entidades Empresariais
    PUBLIC_COMPANY = 2011, 'Empresa Pública'
    MIXED_ECONOMY_COMPANY = 2038, 'Sociedade de Economia Mista'
    OPEN_PUBLIC_COMPANY = 2046, 'Sociedade Anônima Aberta'
    CLOSED_COMPANY = 2054, 'Sociedade Anônima Fechada'
    LIMITED_LIABILITY_COMPANY = 2062, 'Sociedade Empresária Limitada'
    COMPANY_IN_COLLECTIVE_NAME = 2070, 'Sociedade Empresária em Nome Coletivo'
    COMPANY_IN_COMMANDITA_SIMPLES = 2089, 'Sociedade Empresária em Comandita Simples'
    COMPANY_IN_COMMANDITA_BY_SHARES = 2097, 'Sociedade Empresária em Comandita por Ações'
    COMPANY_IN_PARTICIPATION_ACCOUNT = 2127, 'Sociedade em Conta de Participação'
    BUSINESSMAN = 2135, 'Empresário (Individual)'
    COOPERATIVE = 2143, 'Cooperativa'
    APPROVED = 2151, 'Consórcio de Sociedades'
    CONSORTIUM_COMPANIES = 2160, 'Grupo de Sociedades'
    FOREIGN_COMPANY_ESTABLISHMENT_IN_BRAZIL = 2178, 'Estabelecimento, no Brasil, de Sociedade Estrangeira'
    ESTABLISHMENT_IN_BRAZIL_AN_ARGENTINO_BRAZILIAN_BINATIONAL_COMPANY = 2194, 'Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira'
    COMPANY_DOMICILED_ABROAD = 2216, 'Empresa Domiciliada no Exterior'
    INVESTMENT_FUND = 2224, 'Clube/Fundo de Investimento'
    PURE_SIMPLE_SOCIETY = 2232, 'Sociedade Simples Pura'
    SIMPLE_LIMITED_COMPANY = 2240, 'Sociedade Simples Limitada'
    SINGLE_COMPANY_IN_COLLECTIVE_NAME = 2259, 'Sociedade Simples em Nome Coletivo'
    SIMPLE_COMPANY_IN_SIMPLE_COMMANDITA = 2267, 'Sociedade Simples em Comandita Simples'
    BINATIONAL_COMPANY = 2275, 'Empresa Binacional'
    CONSORTIUM_EMPLOYERS = 2283, 'Consórcio de Empregadores'
    SIMPLE_CONSORTIUM = 2291, 'Consórcio Simples'
    INDIVIDUAL_COMPANY_LIMITED_LIABILITY_BUSINESS_NATURE = 2305, 'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)'
    SIMPLE_NATURE_LIMITED_LIABILITY_INDIVIDUAL_COMPANY = 2313, 'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)'
    SOLE_PRACTITIONER_LAW_FIRM = 2321, 'Sociedade Unipessoal de Advogados'
    CONSUMER_COOPERATIVES = 2330, 'Cooperativas de Consumo'
    # 3. Entidades sem Fins Lucrativos
    NOTARY_AND_REGISTRY_SERVICE_NOTARY_PUBLIC = 3034, 'Serviço Notarial e Registral (Cartório)'
    PRIVATE_FOUNDATION = 3069, 'Fundação Privada'
    AUTONOMOUS_SOCIAL_SERVICE = 3077, 'Serviço Social Autônomo'
    CONDOMINIUM_BUILDING = 3085, 'Condomínio Edilício'
    PRIOR_CONCILIATION_COMMITTEE = 3107, 'Comissão de Conciliação Prévia'
    MEDIATION_AND_ARBITRATION_ENTITY = 3115, 'Entidade de Mediação e Arbitragem'
    UNION_BODY = 3131, 'Entidade Sindical'
    ESTABLISHMENT_IN_BRAZIL_FOREIGN_FOUNDATION_OR_ASSOCIATION = 3204, 'Estabelecimento, no Brasil, de Fundação ou Associação Estrangeiras'
    FOUNDATION_OR_ASSOCIATION_DOMICILED_ABROAD = 3212, 'Fundação ou Associação Domiciliada no Exterior'
    RELIGIOUS_ORGANIZATION = 3220, 'Organização Religiosa'
    INDIGENOUS_COMMUNITY = 3239, 'Comunidade Indígena'
    PRIVATE_FUND = 3247, 'Fundo Privado'
    NATIONAL_POLITICAL_PARTY_MANAGEMENT_BODY = 3255, 'Órgão de Direção Nacional de Partido Político'
    REGIONAL_POLITICAL_PARTY_MANAGEMENT_BODY = 3263, 'Órgão de Direção Regional de Partido Político'
    LOCAL_MANAGEMENT_BODY_POLITICAL_PARTY = 3271, 'Órgão de Direção Local de Partido Político'
    POLITICAL_PARTY_FINANCIAL_COMMITTEE = 3280, 'Comitê Financeiro de Partido Político'
    PLEBISCITARY_OR_REFERENDARY_FRONT = 3298, 'Frente Plebiscitária ou Referendária'
    CORPORATE_ORGANIZATION = 3301, 'Organização Social (OS)'
    OTHER_CONDOMINIUMS = 3310, 'Demais Condomínios'
    PRIVATE_MEMBERSHIP = 3999, 'Associação Privada'
    # 4. Pessoas Físicas
    INDIVIDUAL_REAL_ESTATE_COMPANY = 4014, 'Empresa Individual Imobiliária'
    SPECIAL_INSURED = 4022, 'Segurado Especial'
    INDIVIDUAL_TAXPAYER = 4081, 'Contribuinte individual'
    CANDIDATE_FOR_ELECTIVE_POLITICAL_OFFICE = 4090, 'Candidato a Cargo Político Eletivo'
    AUCTIONEER = 4111, 'Leiloeiro'
    INDIVIDUAL_RURAL_PRODUCER = 4120, 'Produtor Rural (Pessoa Física)'
    # 5.Organizações Internacionais e Outras Instituições Extraterritoriais
    INTERNATIONAL_ORGANIZATION = 5010, 'Organização Internacional'
    FOREIGN_DIPLOMATIC_REPRESENTATION = 5029, 'Representação Diplomática Estrangeira'
    OTHER_EXTRATERRITORIAL_INSTITUTIONS = 5037, 'Outras Instituições Extraterritoriais'
